name: CMake CI

on:
  push:
    branches:
      - master
    pull-request: {}

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.4
      with:
        cmake-version: '3.16.x'
    - name: Use cmake
      run: cmake --version
